eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true

logging:
  file:
    name: ./logs/log-file.log

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - logfile

server:
  port: 8080

spring:
  application:
    name: api-gateway
