eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  file:
    name: ./logs/log-file.log

management:
  endpoints:
    web:
      exposure:
        include:
          - helth
          - info
          - logfile

server:
  port: 8020

spring:
  application:
    name: vehicle-service
  data:
    mongodb:
      uri: mongodb://mongodb:mongodb@localhost:27017/
      database: vehicle
      auto-index-creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
