name: ci-develop

on:
  pull_request:
    branches:
      - develop

env:
  JAVA_VERSION: "17"
  MAVEN_VERSION: "3.9.8"

jobs:
  continuous-integration:
    name: Establishment Service
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}
          cache: "maven"
          cache-dependency-path: "**/pom.xml"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build
        working-directory: ./parking-lots-management/establishment-service
        run: mvn -B clean package -DskipTests --no-transfer-progress

      - name: Test
        working-directory: ./parking-lots-management/establishment-service
        run: mvn -B clean test --no-transfer-progress
