services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=establishment
      - TZ=America/Sao_Paulo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U establishment"]
      interval: 30s
      timeout: 10s
      retries: 5
    hostname: postgres
    networks:
      - db
    ports:
      - 5432:5432
    restart: always
    tty: true
    volumes:
      - postgresql:/var/lib/postgresql

  establishment-service:
    image: establishment-service
    build:
      context: ./establishment-service
      dockerfile: Dockerfile
    container_name: establishment-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/establishment
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=America/Sao_Paulo
    hostname: establishment-service
    networks:
      - db
    ports:
      - 8010:8010
    restart: always
    tty: true

networks:
  db:
    driver: bridge

volumes:
  postgresql:
