services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=establishment
      - TZ=America/Sao_Paulo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U establishment"]
      interval: 15s
      timeout: 10s
      retries: 5
    hostname: postgres
    networks:
      - postgres
    ports:
      - 5432:5432
    restart: always
    tty: true
    volumes:
      - postgresql:/var/lib/postgresql

  mongo:
    image: mongo:7.0.5
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - TZ=America/Sao_Paulo
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 15s
      timeout: 10s
      retries: 5
    hostname: mongo
    networks:
      - mongo
    ports:
      - 27017:27017
    restart: always
    tty: true
    volumes:
      - mongodb:/data/db

  establishment-service:
    image: establishment-service
    build:
      context: ./establishment-service
      dockerfile: Dockerfile
    container_name: establishment-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/establishment
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=America/Sao_Paulo
    hostname: establishment-service
    networks:
      - postgres
    ports:
      - 8010:8010
    restart: always
    tty: true

  vehicle-service:
    image: vehicle-service
    build:
      context: ./vehicle-service
      dockerfile: Dockerfile
    container_name: vehicle-service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongo:27017/
      - TZ=America/Sao_Paulo
    hostname: vehicle-service
    networks:
      - mongo
    ports:
      - 8020:8020
    restart: always
    tty: true

networks:
  postgres:
    driver: bridge
  mongo:
    driver: bridge

volumes:
  postgresql:
  mongodb:
